name: 'Secure Build Log Uploader'
description: 'Authenticates with API, uploads GitHub build logs to S3 using temporary credentials, and notifies backend'
author: 'GitHub Actions Plugin'

inputs:
  username:
    description: 'Username for API authentication'
    required: true
  password:
    description: 'Password for API authentication'
    required: true
  api-endpoint:
    description: 'Base URL for the API endpoints (e.g., https://api.example.com)'
    required: true
  github-token:
    description: 'GitHub token for accessing workflow runs and logs'
    required: true
    default: ${{ github.token }}
  workflow-run-id:
    description: 'Specific workflow run ID to analyze (optional, defaults to current run)'
    required: false
  retry-attempts:
    description: 'Number of retry attempts for failed operations'
    required: false
    default: '3'
  retry-delay:
    description: 'Initial delay between retries in seconds'
    required: false
    default: '2'

outputs:
  s3-url:
    description: 'S3 URL where logs were uploaded'
  upload-status:
    description: 'Status of the upload process (success, failed)'
  files-uploaded:
    description: 'Number of files uploaded'
  auth-status:
    description: 'Authentication status (success, failed)'
  user-info:
    description: 'JSON string containing authenticated user information'
  notification-status:
    description: 'Status of the upload notification (success, failed)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'
