name: 'Hycos AI Log Analyzer'
description: 'Uploads GitHub build logs for AI-powered analysis and debugging insights'
author: 'Hycos AI'

inputs:
  api-key:
    description: 'Hycos AI API authentication key'
    required: true
  api-endpoint:
    description: 'Base URL for the Hycos AI API endpoints (for enterprise users)'
    required: false
    default: 'https://grgikf0un8.execute-api.us-east-1.amazonaws.com/dev2'
  github-token:
    description: 'GitHub token for accessing workflow runs and logs'
    required: true
    default: ${{ github.token }}
  workflow-run-id:
    description: 'Specific workflow run ID to analyze (optional, defaults to current run)'
    required: false

outputs:
  analysis-url:
    description: 'Direct link to Hycos AI analysis: https://app.hycos.ai/ci-analysis/{analysisId}'
  analysis-id:
    description: 'Unique analysis identifier'
  upload-status:
    description: 'Status of the process (success, failed)'
  files-uploaded:
    description: 'Number of files processed'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'
