name: 'Hycos AI Log Analyzer'
description: 'Uploads GitHub build logs to S3 for AI-powered analysis and debugging insights'
author: 'Hycos AI'

inputs:
  api-key:
    description: 'Hycos AI API authentication key'
    required: true
  api-endpoint:
    description: 'Base URL for the Hycos AI API endpoints'
    required: false
    default: 'https://lnjh7eud9a.execute-api.us-east-1.amazonaws.com/dev'
    # TODO: Change to 'https://api.hycos.ai' when available
  github-token:
    description: 'GitHub token for accessing workflow runs and logs'
    required: true
    default: ${{ github.token }}
  workflow-run-id:
    description: 'Specific workflow run ID to analyze (optional, defaults to current run)'
    required: false
  retry-attempts:
    description: 'Number of retry attempts for failed operations'
    required: false
    default: '3'
  retry-delay:
    description: 'Initial delay between retries in seconds'
    required: false
    default: '2'
  s3-log-path:
    description: 'Custom S3 path prefix for log storage'
    required: false
    default: 'logs'

outputs:
  analysis-url:
    description: 'Direct link to Hycos AI analysis: https://app.hycos.ai/ci-analysis/{analysisId}'
  analysis-id:
    description: 'Unique analysis identifier'
  upload-status:
    description: 'Status of the upload process (success, failed)'
  files-uploaded:
    description: 'Number of files uploaded'
  s3-url:
    description: 'S3 URL where logs were uploaded'
  notification-status:
    description: 'Status of the upload notification (success, failed)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'
