name: Local Test
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies and build action
        run: |
          npm ci --no-audit --no-fund
          npm run package
      - uses: ./ # ← ‘./’ means “use the action in this folder”
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # api-endpoint: 'http://54.89.53.140:8080/'
          api-endpoint: 'https://55k1jx7y6e.execute-api.us-east-1.amazonaws.com/dev/'
          github-token: ${{ secrets.GITHUB_TOKEN }}
